### PR TITLE
infra: enhance error message with grpc callback when port is in use

### PR DESCRIPTION
**Pull request by ertosns**
fix to #1398

### CODE REVIEW

**Comment by canepat** [comment]
Thank you for your contribution!

Unfortunately, this PR is not ready to be considered for fixing #1398 due to the following reasons:
- the issue explicitly asks for improving the error message in the gRPC server, your change is printing a console message
- the unit test is not testing anything, it just registers the gRPC callback w/o triggering any invocation
- the way you're plugging the unit test in is unnecessarily changing the build procedure, instead it's sufficient to follow the existing naming conventions for other tests
- the linter complains about broken conventions

**Comment by canepat** [comment]
@ertosns are you willing to work on this PR in the upcoming weeks?

**Comment by ertosns** [comment]
Thanks for your feedback! @canepat 

no problem i can fix that.

**Comment by canepat** [comment]
I'm going to close this PR next week if there is no activity

**Pull request closed without merging**
